Magic_Inventory/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magic_Inventory.Data;
using Magic_Inventory.Models;
using CreditCardValidator;

namespace Magic_Inventory.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private bool CreditCardVerified = false;
        private static string OrderNumber = " ";

        public CartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Carts Displays the cat to users
        public async Task<IActionResult> Index(int? cartID,String val)
        {
            ViewData["CardV"] = CreditCardVerified;
            Cart newQuantity = new Cart();
            if (! String.IsNullOrEmpty(val))
                if (cartID != null)
                {
                    try
                    {
                        newQuantity = _context.Cart.Where(s => s.CartID == cartID).Single();
                    }
                    catch
                    {
                        var applicationDbContext2 = _context.Cart.Include(c => c.Product).Include(c => c.Store);
                        return View(await applicationDbContext2.ToListAsync());
                    }
                    StoreInventory si = _context.StoreInventory.Where(a => a.StoreID == newQuantity.StoreID).Where(m => m.ProductID == newQuantity.ProductID).Single();
                    if (val.Equals("+") && si.StockLevel > 0)
                    {
                        newQuantity.Quantity++;
                        si.StockLevel--;
                    }
                    else if (val.Equals("-"))
                    {
                        newQuantity.Quantity--;
                        si.StockLevel++;
                    }
                    if (newQuantity.Quantity <= 0)
                        _context.Cart.Remove(newQuantity);
                    else
                        _context.Update(newQuantity);
                    _context.Update(si);
                    _context.SaveChanges();
                    val = "";
                }
            var applicationDbContext = _context.Cart.Include(c => c.Product).Include(c => c.Store).Where(l=>l.UserName == User.Identity.Name.ToString());
            int totalitem = 0;
            double totalcost =0;
            foreach (var item in applicationDbContext)
            {
                totalitem += item.Quantity;
                totalcost = totalcost + (item.Quantity * item.Price);
            }
            ViewData["item"] = totalitem;
            ViewData["cost"] = totalcost;
            return View(await applicationDbContext.ToListAsync());
        }

        //Using apackage to validate crfedit cards
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult VerifyCreditCard()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerifyCreditCardNow(string cardNumber)
        {
            //Verify the card using CreditCardValidator 
            CreditCardDetector detector = new CreditCardDetector(cardNumber);

            if (detector.IsValid())
            {
                CreditCardVerified = true;
                bool result = await UpdateCartAndOrderHistoryAsync();
                return Redirect(nameof(Invoice));
            }
                ViewBag.ErrorCard = CreditCardVerified;
                return View(nameof(VerifyCreditCard)); 
        }

        //will work at the check out. before desplaying the invoice
        private async Task<bool> UpdateCartAndOrderHistoryAsync()
        {
            if (CreditCardVerified)
            {                
                var cartItem = _context.Cart.Where(s => s.UserName == User.Identity.Name.ToString());
                
                var orderNo = new OrderHistory().OrderNumber;
                
                orderNo = DateTime.Now.ToString("hhmmssddMMyy") + User.Identity.Name.ToString();
                OrderNumber = orderNo;
                foreach (var item in cartItem)
                {
                    var orderHistory = new OrderHistory();
                    orderHistory.OrderDate = DateTime.Now;
                    orderHistory.ProductID = item.ProductID;
                    orderHistory.StoreID = item.StoreID;
                    orderHistory.Quantity = item.Quantity;
                    orderHistory.UserName = item.UserName;
                    orderHistory.Price = item.Price;
                    orderHistory.OrderNumber = orderNo;
                    _context.OrderHistory.Add(orderHistory);
                    _context.Cart.Remove(item);
                }
                await _context.SaveChangesAsync();
                return true;
            }
            return false;
        }

        //Displays receipt of the products bought at this time
        public IActionResult Invoice()
        {
            if (!OrderNumber.Equals(""))
            {
                var context2 = _context.OrderHistory.Include(z => z.Product).Include(n => n.Store).Where(m => m.OrderNumber == OrderNumber);
                int totalitem2 = 0;
                double totalcost2 = 0;
                foreach (var item in context2)
                {
                    totalitem2 += item.Quantity;
                    totalcost2 = totalcost2 + (item.Quantity * item.Price);
                    ViewData["date"] = item.OrderDate.ToString("dd/mm/yyyy");
                    ViewData["number"] = item.OrderNumber;
                    ViewData["name"] = item.UserName;
                }
                ViewData["item"] = totalitem2;
                ViewData["cost"] = totalcost2;
                
                return View(context2);
            }
            return NotFound();
        }

        //calls the view which then uses angular and WebApi to fetch data
        public IActionResult OrderHistory()
        {
            @ViewBag.UserName = User.Identity.Name;
            return View();
        }
                
        // Displays the page that asks the user to confirm delete
        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .Include(c => c.Product)
                .Include(c => c.Store)
                .SingleOrDefaultAsync(m => m.CartID == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // once confirmed delete the data from database here
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CartID)
        {
            var cart = await _context.Cart.SingleOrDefaultAsync(m => m.CartID == CartID);
            if (cart != null)
            {
                StoreInventory si = _context.StoreInventory.Where(a => a.StoreID == cart.StoreID).Where(m => m.ProductID == cart.ProductID).Single();
                si.StockLevel += cart.Quantity;
                _context.StoreInventory.Update(si);
                _context.Cart.Remove(cart);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
            return _context.Cart.Any(e => e.CartID == id);
        }
    }
}

Magic_Inventory/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magic_Inventory.Data;
using Magic_Inventory.Models;
using Microsoft.AspNetCore.Authorization;

namespace Magic_Inventory.Controllers
{
    [Authorize(Roles = RoleConstants.CustomerRole)]
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Display product list. search. filtering enabled
        public async Task<IActionResult> Index(string searchName,string store)
        {
            ViewData["searchName"] = "";
            ViewData["store"] = "";

            //For searching by store
            var StoreLst = new List<string>();
            var StoreQry = _context.Store.Select(m => m.Name);
            StoreLst.AddRange(StoreQry.Distinct());            
            ViewBag.StoreName = new SelectList(StoreLst,store);

            var applicationDbContext = _context.StoreInventory.Include(s => s.Product).Include(m => m.Store).Where(d => d.StockLevel > 0);
            if (!String.IsNullOrEmpty(searchName))
            {
                ViewData["searchName"] = searchName;
                if (!String.IsNullOrEmpty(store))
                {
                    //Tricky way to get things done. error free
                    ViewData["store"] = store;
                    var applicationDbContext3 = _context.StoreInventory.Include(s => s.Product).Include(m => m.Store).Where(s => s.Product.Name.Contains(searchName)).Where(h=>h.Store.Name == store).Where(d=>d.StockLevel >0);
                    return View(await applicationDbContext3.ToListAsync());
                }
                
                var applicationDbContext2 = _context.StoreInventory.Include(s => s.Product).Include(m => m.Store).Where(s => s.Product.Name.Contains(searchName)).Where(d => d.StockLevel > 0);
                return View(await applicationDbContext2.ToListAsync());
            }
            if (!String.IsNullOrEmpty(store))
            {
                ViewData["store"] = store;
                var applicationDbContext2 = _context.StoreInventory.Include(s => s.Product).Include(m => m.Store).Where(s => s.Store.Name == store).Where(d => d.StockLevel > 0);
                return View(await applicationDbContext2.ToListAsync());
            }

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> AddToCart(int? Quantity,int? ProductID, int? StoreID,string searchName,string store)
        {
            Console.WriteLine(searchName);
            if (ProductID == null || StoreID == null || Quantity == null)
            {
                return NotFound();
            }
            var temp = _context.Cart.Where(z => z.UserName == User.Identity.Name.ToString()).Where(c => c.ProductID == (int)ProductID).Where(m => m.StoreID == StoreID).SingleOrDefault();
            if (temp == null)
            {
                //Updating the tem value
                var cartItem = new Cart();
                cartItem.StoreID = (int)StoreID;
                cartItem.ProductID = (int)ProductID;
                cartItem.Quantity = (int)Quantity;
                cartItem.UserName = User.Identity.Name.ToString();
                cartItem.Price = await _context.Product.Where(c => c.ProductID == (int)ProductID).Select(c => c.Price).SingleOrDefaultAsync();
                cartItem.CartEntryDate = DateTime.Today;
                _context.Cart.Add(cartItem);               
            }
            else
            {
                temp.Quantity += (int)Quantity;
            }
            var reduceTemp = _context.StoreInventory.Where(p => p.ProductID == (int)ProductID).Where(m => m.StoreID == (int)StoreID).SingleOrDefault();
            reduceTemp.StockLevel = reduceTemp.StockLevel - (int)Quantity;
            // Updating the database
            await _context.SaveChangesAsync();
            return RedirectToAction("Index",new { @searchName = searchName,@store = store});
        }
    }
}

Magic_Inventory/Controllers/OwnerInventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Magic_Inventory.Data;
using Magic_Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Magic_Inventory.Controllers
{
    [Authorize(Roles = RoleConstants.OwnerRole)]
    public class OwnerInventoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OwnerInventoriesController(ApplicationDbContext context) {
            _context = context;

        }

        // Show owner Inventory
        public async Task<IActionResult> Index()
        {
            var ownerInventoryList = _context.OwnerInventory.Include(o => o.Product);
            return View(await ownerInventoryList.ToListAsync());
        }

        //test
        // GET: OwnerInventories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {                
                return NotFound();
            }          
            var ownerInventory = await _context.OwnerInventory.Include(o => o.Product).SingleOrDefaultAsync(m => m.ProductID == id);
            if (ownerInventory == null)
            {
                return NotFound();
            }
           
            ViewBag.ProductName = ownerInventory.Product.Name;
            return View(ownerInventory);
        }

        // POST: OwnerInventories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,StockLevel")] OwnerInventory ownerInventory)
        {
            if (id != ownerInventory.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {              
                    try
                    {
                        _context.Update(ownerInventory);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!OwnerInventoryExists(ownerInventory.ProductID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }              

                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Name", ownerInventory.ProductID);
            return View(ownerInventory);
        }
        
        // GET: OwnerInventories/Refill
        public async Task<IActionResult> Refill(int? id)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
                // return NotFound();
            }
            var ownerInventory = await _context.OwnerInventory.Include(o => o.Product).SingleOrDefaultAsync(m => m.ProductID == id);
            if (ownerInventory == null)
            {
                return NotFound();
            }            
            ViewBag.ProductName = ownerInventory.Product.Name;
            return View(ownerInventory);
        }

        // POST: OwnerInventories/Refill        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Refill(int id, [Bind("ProductID,StockLevel")] OwnerInventory ownerInventory)
        {
            if (id != ownerInventory.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ownerInventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OwnerInventoryExists(ownerInventory.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "StockRequests");
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Name", ownerInventory.ProductID);
            return View(ownerInventory);
        }


        private bool OwnerInventoryExists(int id)
        {
            return _context.OwnerInventory.Any(e => e.ProductID == id);
        }
       
    }
}

Magic_Inventory/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Magic_Inventory.Models
@using Magic_Inventory.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magic_Inventory</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
       
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
       
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Magic_Inventory</a>
            </div>            
            <div class="navbar-collapse collapse">
                @if (SignInManager.IsSignedIn(User))
                {                  
                    if (User.IsInRole(RoleConstants.OwnerRole))
                    {
                                    <ul class="nav navbar-nav">
                                        <li><a asp-area="" asp-controller="OwnerInventories" asp-action="Index">Product List</a></li>
                                       <li><a asp-area="" asp-controller="StockRequests" asp-action="Index">Stock Requests</a></li>                                       
                                    </ul>
              
                     }
                     if (User.IsInRole(RoleConstants.FranchiseHolderRole))
                    {
                                    <ul class="nav navbar-nav">
                                       
                                        <li><a asp-area="" asp-controller="StoreInventories" asp-action="Index">Product List</a></li>
                                        <li><a asp-area="" asp-controller="StockRequests" asp-action="CreateNewItemRequest">New Item Requests</a></li>
                                        <li><a asp-area="" asp-controller="StockRequests" asp-action="StoreStockRequests">Stock Requests</a></li>                                       
                                    </ul>
              
                     }
                    if (User.IsInRole(RoleConstants.CustomerRole))
                    {
                                    <ul class="nav navbar-nav">

                                        <li><a asp-area="" asp-controller="Customers" asp-action="Index">Product List</a></li>
                                        <li><a asp-area="" asp-controller="Carts" asp-action="Index">Shopping cart</a></li>
                                        <li><a asp-area="" asp-controller="Carts" asp-action="OrderHistory">Order history</a></li>                                        
                                    </ul>
              
                     }
                }
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><a asp-action="Contact" asp-controller="Home"> &copy; 2018 - Magic_Inventory </a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>